### ISSUE TITLE
No result shown

### ISSUE THREAD

**Issue by pcav** [mach0/polystrip#1]
When clicking on OK, apparently nothing happens.
Same thing for OK.
Thanks for checking.

**Comment by mach0** [comment]
Hi!
Still marked as experimental. I did not have the time yet to catch wrong usage (though I know the usage may currently not be obvious - maybe I should put it into the README).

You have to have a Line Vectorlayer and a feature of that line leayer selected before clicking on ok.
And there is definitely room for Unit handling (as currently the "layer"-Units will be used) and much more.
But you know - time is always a limiting factor ;)

**Comment by pcav** [comment]
Thanks for the explanation. I missed the fact that I had to select a feature: now it works.
