### ISSUE TITLE
Last Polygon is off angled

### ISSUE THREAD

**Issue by tveinot** [mach0/polystrip#2]
Hi;
Great tool! been using it to make map sheets along streets. 
Something I noticed is that the last polygon is about 45 degrees off of the strip created by all the other polygons and it doesn't cover the final section of line. I am pretty sure it is the last polygon as defined by the digitized line direction.
Easy fix if you are only doing a few lines at a time, can be an issue if using this on larger numbers.

**Comment by mach0** [comment]
Hi!
Just ported the tool to QGIS3.x so maybe there are some itches. 
Pull requests are welcome if you find out why the last one is distorted. :)

**Comment by tveinot** [comment]
Not much of a developer so I likely wouldn't be able to track down the issue. You say ported to QGIS3, does that mean it was/is also available for QGIS2.18.x? I didn't see it in the plugin manager.

**Comment by mach0** [comment]
Yes - version 0.1 was available for QGIS 2.18 as experimental version too.
Maybe there is an issue, as there is no maximum QGIS version set for that release.
But IIRC I could download it via plugin manager and it has been downloaded 1104 times (so that could not be me along ;) )

**Comment by tveinot** [comment]
I found it, experimental plug-ins must have been off when I last checked. The 2.18.x works perfectly and does not seem to have a tilted polygon at the end. If I was to run it on many lines I would likely use it in 2.18.x
Still though I am very impressed with this tool, it has many use implications, thanks again for sharing your work.

**Comment by mach0** [comment]
@tveinot 
credits go to 
https://gis.stackexchange.com/questions/173127/generating-equal-sized-polygons-along-line-with-pyqgis
I only made a plugin out of it and fixed some bugs.

**Comment by mach0** [comment]
maybe the new version fixes that angle problem too - can you please test the new version?

**Comment by tveinot** [comment]
Sorry, getting the email that the issue was closed reminded me to check this out. The oddly rotated polygon is no longer generated. Thank you; this is a great tool for making map sheets along roads and other network features.
