### ISSUE TITLE
Python error - plugin doesn't work

### ISSUE THREAD

**Issue by draken76** [mach0/polystrip#3]
In QGIS 3.4.4
When executing  plugin

 _WARNING    Traceback (most recent call last):
              File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\xxx/python/plugins\polystrip\poly_strip.py", line 191, in run
              self.dlg.polystrip(layer)
              File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\xxx/python/plugins\polystrip\poly_strip_dialog.py", line 51, in polystrip
              getAllPages(layer, width, height, srid, coverage)
              File "C:/Users/xxx/AppData/Roaming/QGIS/QGIS3\profiles\xxx/python/plugins\polystrip\poly_strip_alg.py", line 69, in getAllPages
              azimuth = startpoint.asPoint().azimuth(endpoint.asPoint())
             ValueError: Null geometry cannot be converted to a point._

Im not a programist, I don't know what to do with that.

**Comment by mach0** [comment]
thank you for your comment.
As the plugin is still marked as experimental and my time is currently limited I would welcome contribution.
I will try to fix the bug. To me it looks that there is no line layer loaded or selected.
The plugin in its current version is not catching user-errors and does not have good documentation (see above - lack of time). You first have to load and select a line before using the plugin . - hope that helps

**Comment by draken76** [comment]
Hi!
Thanks for your answer.

Line was added and selected. Whats more, I had your plugin working, and I
was using it many times before.
I still have it working in my office on QGIS 3.2. I have this python
problem in my home computer with QGIS 3.4.4.

Because I was using your plugin many times, friends asked me to make a
tutorial. And I created some data to show how to use polystrip along with
atlas feature.
[image: 01.png]
What you can see above proves that I was succesfull with polystrip. Ok,
let's remove this layer created some time ago in QGIS 3.2
Now it looks like that:
Let's try it with the same line...
[image: 02.png]

Select line...
[image: 03.png]

Start plugin...
[image: 04.png]

And... Kaboom...
[image: 05.png]

But, as I mentioned, I'm not a programmer, and don't know what to do.
[image: 06.png]

Of course, I will make this tutorial on 3.2, but I'm affraid thet ma
colegues will ask: I'ts not working! Why???
So, please, try to find time to check what happened.

Best regards

Bartosz


pt., 1 lut 2019 o 14:53 Werner Macho <notifications@github.com> napisał(a):

**Comment by mach0** [comment]
should work with 3.4 again.
Could you please test?

**Comment by mach0** [comment]
solved after confirmation
